# Generated by Django 5.2.7 on 2025-11-01 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricão', models.DateField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('status_beneficio', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECEBIDO', 'BENEFÍCIO RECEBIDO'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10, verbose_name='Status do Benefício')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='members.member')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Programa')),
                ('tipo', models.CharField(choices=[('BOLSA', 'Bolsa'), ('AUXILIO', 'Auxílio'), ('EVENTO', 'Evento'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Programa')),
                ('regras_eleigibilidade', models.TextField(blank=True, null=True, verbose_name='Regras de Elegibilidade')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('membros_inscritos', models.ManyToManyField(blank=True, related_name='programas_inscritos', through='programs.Enrollment', to='members.member')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='programs.program'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('membro', 'programa')},
        ),
    ]
