# Generated by Django 5.2.7 on 2025-11-03 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_nome_member_nome_completo'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='regras_eleigibilidade',
            new_name='regras_elegibilidade',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='data_inscricão',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='status_beneficio',
        ),
        migrations.RemoveField(
            model_name='program',
            name='membros_inscritos',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='data_inscricao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Inscrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECEBIDO', 'Benefício Recebido'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10, verbose_name='Status do Benefício'),
        ),
        migrations.AddField(
            model_name='program',
            name='membros_partipantes',
            field=models.ManyToManyField(blank=True, related_name='programas_participantes', through='programs.Enrollment', to='members.member'),
        ),
    ]
