# Generated by Django 6.0 on 2026-01-08 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(default=django.utils.timezone.now, verbose_name='Mês de Referência')),
                ('total_membros', models.IntegerField(default=0, verbose_name='Total de Membros')),
                ('total_receitas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_despesas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
            ],
            options={
                'verbose_name': 'Relatório Mensal',
                'verbose_name_plural': 'Relatórios Mensais',
            },
        ),
    ]
