# Generated by Django 6.0 on 2026-01-06 14:07

import finances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialentry',
            name='descriacao',
        ),
        migrations.AddField(
            model_name='financialentry',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to=finances.models.comprovante_upload_path, verbose_name='Comprovante / Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='financialentry',
            name='descricao',
            field=models.CharField(default='Lancamento Antigo', max_length=255, verbose_name='Descrição (Ex: Conta de Luz)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria (Ex: Alimentação, Transporte)'),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='tipo',
            field=models.CharField(choices=[('RECEITA', 'Receita (Entrada)'), ('DESPESA', 'Despesa (Saída)')], max_length=10, verbose_name='Tipo de Lançamento'),
        ),
    ]
