# Generated by Django 5.2.7 on 2025-10-30 22:03

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, unique=True, verbose_name='RG')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('telefone_contato', models.CharField(max_length=20, verbose_name='Telefone de Contato')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to=members.models.get_profile_image_path, verbose_name='Foto de Perfil')),
                ('situacao', models.CharField(choices=[('REGULAR', 'Regular'), ('IRREFULAR', 'Irregular'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=10, verbose_name='Situação do Membro')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Ultima Atualização')),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
            },
        ),
    ]
