# Generated by Django 5.2.7 on 2025-11-01 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='nome',
            new_name='nome_completo',
        ),
    ]
