# Generated by Django 5.2.7 on 2025-11-03 13:07

import django.db.models.deletion
import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_nome_member_nome_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='parentes',
            field=models.ManyToManyField(blank=True, to='members.member', verbose_name='Parentes'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição do Documento')),
                ('arquivo', models.FileField(upload_to=members.models.comprovante_upload_path, verbose_name='Arquivo (PDF, Imagem)')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='members.member', verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Documento do Membro',
                'verbose_name_plural': 'Documentos dos Membros',
            },
        ),
    ]
